#!/bin/bash

cd "$(dirname "$0")"/..

VENV_NAME="env"

if [ ! -d "$VENV_NAME" ]; then
    python3 -m venv "$VENV_NAME"
fi
. "$VENV_NAME/bin/activate"

python -m pip install --upgrade pip
python -m pip install -r requirements.txt

echo ""
echo "Run source $VENV_NAME/bin/activate to activate the virtualenv"
echo ""